site_name: TheMoeWay
site_description: Moe Moe Moe Moe Moe Moe Moe
site_url: https://learnjapanese.moe
site_author: shoui  
repo_url: https://github.com/shoui520/shoui520.github.io
repo_name: Open a pull request
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'Japanese Guide': 'guide.md'
    - '30 Day Japanese': 'routine.md'
    - 'The Shoui Method': 'shouimethod.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'readingtips.md'
    - 'monolingual.md'
    - 'faq.md'
    - 'Fixing your font': 'font.md'
    - 'How to use 5ch': '2ch.md'
    - 'ime.md'
  - 'Visual Novels':
    - 'Learning Japanese with VNs': 'vn.md'
    - 'Visual Novel Setup': 'vn-setup.md'
  - 'Yomitan':
    - 'Yomitan Setup Tutorial': 'yomichan.md'
    - 'Anki & Mining': 'mining.md'   
    - 'One-Click Anime Cards': 'autocards.md'
    - 'Mobile Reading Setup': 'mobile-reading.md'   
  - 'Resources':
    - 'Resources': 'resources.md' 
  - 'Other':
    - 'Donate': 'donate.md'
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  custom_dir: overrides
  favicon: img/favicon.png
  logo: img/moe.svg
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/lang.js
plugins:
  - search:
      lang:
        - en
        - ja
  - open-in-new-tab
