site_name: TheMoeWay
site_description: Moe Moe Moe Moe Moe Moe Moe
site_url: https://learnjapanese.moe
site_author: shoui  
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'Japanese Guide': 'guide.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'reading.md'
    - 'monolingual.md'
    - 'faq.md'
    - 'Fixing your font': 'font.md'
  - 'Visual Novels':
    - 'Learning Japanese with VNs': 'vn.md'
    - 'Visual Novel Setup': 'vn-setup.md'
  - 'Yomichan':
    - 'Yomichan Setup Tutorial': 'yomichan.md'      
  - 'Resources':
    - 'Resources': 'resources.md' 
  - 'Other':
    - 'Donate': 'donate.md'
theme:
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  custom_dir: overrides
  palette:
    # Light mode
      - scheme: default
        primary: blue
        accent: cyan      
  favicon: img/favicon.png
  logo: img/moe.svg
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
  - javascripts/extra.js
plugins:
  - search:
      lang:
        - en
        - ja
